# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y make gcc

COPY . /dbcc
WORKDIR /dbcc
RUN make

FROM ubuntu:20.04 as package
COPY --from=builder /dbcc/dbcc /
